a=10
print(type(a))
b=0.5
print(type(b))
a="sravani"
print(type(a))
l=[1,3,"hema",0.5]
print(type(l))
t=(1,3,7,9.0)
print(type(t))
d={"name":"srav","age":35}
d={"name":"srav","age":35}
print(type(d))
s=set()
s=(1,2,3)
print(type(s))
s={1,2,3,4}
print(type(s))
t=tuple()
print(type(t))